# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
# null vector = zero vector
nullVector = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [3]:
vector = np.arange(10, 50)

4. Find the shape of previous array in question 3

In [4]:
# shape = rows x cols
vector.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
vector.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__, end='\n\n')
np.show_config()

1.19.4

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


7. Print the dimension of the array in question 3


In [7]:
# ndim = dimensions/ axes
vector.ndim

1

8. Create a boolean array with all the True values

In [8]:
booleanArray = np.ones(10, dtype=bool)
booleanArray

# OR

booleanArray = np.full((1,10), True)
booleanArray

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

9. Create a two dimensional array




In [9]:
twoDArray = np.array([[1, 2, 3], [4, 5, 6]])
print(twoDArray)

# OR

twoDArray = np.arange(1, 7).reshape(2,3)
twoDArray

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

10. Create a three dimensional array



In [10]:
threeDArray = np.arange(27).reshape(3,3,3)
threeDArray

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
vector = np.arange(10)
vector[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
nullVec = (np.arange(10) == 5) * 1
nullVec                                                                 # nullVec = np.arange(10)
                                                                        # nullVec = nullVec == 5
                                                                        # nullVec = nullVec * 1


array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [13]:
identityMatrix = np.eye(3,3)
identityMatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

floatArr = arr.astype(np.float64)
floatArr.dtype

int32


dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

product = arr1 * arr2
product

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

comparisonArray = arr1 == arr2
comparisonArray

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
# odd = [np.arange(10)%2!=0] ###
odd = np.arange(10)
np.place(odd, odd%2 == 0, 0)
odd = odd[odd > 0]
odd

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
np.place(odd, odd!=0, -1)
odd

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)

# index = [5,6,7]
# arr[index] = 12

arr[[5,6,7]] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
twoDArr = np.zeros((2,5))
twoDArr[0][0] = 1
twoDArr[0][-1] = 1
twoDArr[1][0] = 1
twoDArr[1][-1] = 1
twoDArr

array([[1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
array = np.arange(10).reshape(2,5)[0]
array

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
array = np.arange(10).reshape(2,5)[1]
array

array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
array = np.arange(10).reshape(2,5)[[0, 1], [2]]
array

array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
randomArr = np.random.randint(0, 20, size = (10,10))

print(randomArr.min())
randomArr.max()

0


19

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [28]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

# data[(names == 'Will')] # index -> 2, 4 printing whole rows @ indices 2 and 4
data[~(names == 'Will')]

array([[ 1.67725218,  1.08133207,  1.58218103,  1.64732437],
       [ 1.23277136,  0.05455434, -0.24458909, -1.90224615],
       [ 0.56275127,  1.83486389, -0.16870471, -1.40261346],
       [ 0.6353954 ,  0.76753574,  0.12947389, -1.13094978],
       [-0.43194881,  0.24325714,  0.82216624,  1.53031711]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

data[~(names == 'Will')& ~(names == 'Joe')]

array([[-1.09119182, -1.18572479,  2.10176965, -1.86963896],
       [ 1.24519301, -0.63158931,  0.0419341 , -2.85223973]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [30]:
twodarray = np.arange(1,16).reshape(5, 3)
twodarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [31]:
threedarray = np.arange(1,17).reshape(2, 2, 4)
threedarray

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [32]:
threedarray.swapaxes(0,1) # is swapping axes and matrix transpose the same thing???

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [33]:
arrr = np.sqrt(np.arange(10))
np.place(arrr, arrr>0.5, 0)
arrr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [34]:
arr1 = np.random.randint(0, 12, size = (5))
arr2 = np.random.randint(0, 12, size = (5))
arr3 = np.maximum(arr1, arr2)
print(arr1)
print('############')
print(arr2)
print('############')
arr3

[6 8 6 1 9]
############
[10  6  2 11  4]
############


array([10,  8,  6, 11,  9])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [35]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

uniqueNames = np.unique(names)
np.sort(uniqueNames)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [36]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

a[~np.isin(a, b)]


array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [37]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

# sampleArray[:, [1]] = newColumn

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [38]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

dotP = np.dot(x, y)
dotP

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [39]:
randomMatrix = np.random.randint(1, 100, size = (20))
np.cumsum(randomMatrix)

array([  70,  121,  138,  205,  220,  277,  303,  350,  448,  465,  554,
        625,  657,  679,  730,  826,  839,  880,  969, 1004], dtype=int32)