# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr1 = np.arange(10, dtype = 'int32').reshape(2,5)
arr2 = np.ones(10, dtype = 'int32').reshape(2,5)
np.vstack((arr1, arr2)) # tuple

# vertical stack => number of rows will increase

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
arr1 = np.arange(10, dtype = 'int32').reshape(2,5)
arr2 = np.ones(10, dtype = 'int32').reshape(2,5)
np.hstack((arr1, arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
arr1 = np.array([[0,1,2,3,4], [5,6,7,8,9]])
arr1 = np.ravel(arr1)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
higher_to_lower = np.arange(15).reshape(3,5)
higher_to_lower.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
one_to_higher = np.arange(15).reshape(5,3)
one_to_higher

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
five_by_five = np.random.randint(1,10, (5,5))
print(five_by_five)
print('\nSQUARE')
np.square(five_by_five)

[[7 5 7 2 5]
 [4 5 9 7 1]
 [9 3 4 5 1]
 [4 2 2 3 8]
 [3 6 7 5 9]]

SQUARE


array([[49, 25, 49,  4, 25],
       [16, 25, 81, 49,  1],
       [81,  9, 16, 25,  1],
       [16,  4,  4,  9, 64],
       [ 9, 36, 49, 25, 81]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [8]:
five_by_six = np.random.randint(1,11, (5,6))
np.mean(five_by_six)
# manually
# np.sum(five_by_six)/(5*6)

5.966666666666667

## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
np.std(five_by_six)

3.0053655721429675

## Question:10

### Find the median of the previous array in Q8?

In [10]:
np.median(five_by_six)

7.0

## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
np.transpose(five_by_six)

array([[ 7, 10,  7,  3,  9],
       [ 7, 10,  9,  9,  5],
       [ 9,  2,  1,  4,  1],
       [10,  4,  8,  2,  7],
       [ 2,  4, 10,  5,  4],
       [ 7,  7,  2, 10,  4]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
four_by_four = np.arange(16).reshape(4, 4)
np.sum(np.diagonal(four_by_four))
# np.diag(four_by_four) ####### what is the diff?!?!
# print(np.sum(np.diagonal(four_by_four))) # same answer

30

## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
np.linalg.det(four_by_four)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
arr = np.arange(10)
np.percentile(arr, (5, 95))

array([0.45, 8.55])

## Question:15

### How to find if a given array has any null values?

In [15]:
# generating an array 0-49 and 5 random null values (np.nan)
arr = np.arange(50, dtype=float).reshape(10, 5)
nulls = 5
null_indexes = np.random.choice(arr.size, nulls, replace =  False) 
# replace = False => NO REPEATED VALUES/ GIVES ONLY UNIQUE SAMPLES
# if replace = True (default) => sometimes the null_indexes might have duplicate values
# and we get less than 5 (nulls) np.nans
arr.ravel()[null_indexes] = np.nan
np.isnan(arr)
f'Total null values are {np.sum(np.isnan(arr))}'

'Total null values are 5'